"""Command-line parser construction for Azathoth."""

from argparse import ArgumentParser

from azathoth import __version__
from azathoth.cli.parsing.benchmarks import (
    BENCHMARK_ACTION_ATTRIBUTE,
    BENCHMARK_CASE_ID_ATTRIBUTE,
    BENCHMARK_CASE_SHOW_ACTION,
    BENCHMARK_CASES_ACTION,
    BENCHMARK_COMMAND,
    BENCHMARK_COMPARE_ACTION,
    BENCHMARK_DOCUMENT_ATTRIBUTE,
    BENCHMARK_ID_ATTRIBUTE,
    BENCHMARK_IMPORT_ACTION,
    BENCHMARK_LIST_ACTION,
    BENCHMARK_OUTPUT_ATTRIBUTE,
    BENCHMARK_RUN_ACTION,
    BENCHMARK_SHOW_ACTION,
    BENCHMARK_WORKFLOW_IDS_ATTRIBUTE,
    add_benchmark_parser,
)
from azathoth.cli.parsing.common import COMMAND_ATTRIBUTE
from azathoth.cli.parsing.experiments import (
    EXPERIMENT_ACTION_ATTRIBUTE,
    EXPERIMENT_COMMAND,
    EXPERIMENT_ID_ATTRIBUTE,
    EXPERIMENT_SHOW_ACTION,
    add_experiment_parser,
)
from azathoth.cli.parsing.goals import (
    GOAL_ACTION_ATTRIBUTE,
    GOAL_COMMAND,
    GOAL_DOCUMENT_ATTRIBUTE,
    GOAL_ID_ATTRIBUTE,
    GOAL_IMPORT_ACTION,
    GOAL_LIST_ACTION,
    GOAL_SHOW_ACTION,
    add_goal_parser,
)
from azathoth.cli.parsing.models import (
    MODEL_ACTION_ATTRIBUTE,
    MODEL_AUTHORIZE_ACTION,
    MODEL_COMMAND,
    MODEL_DEAUTHORIZE_ACTION,
    MODEL_FORCE_ATTRIBUTE,
    MODEL_IDENTIFIER_ATTRIBUTE,
    MODEL_LIST_ACTION,
    MODEL_PORTFOLIO_ACTION,
    MODEL_SHOW_ACTION,
    MODEL_USAGE_ACTION,
    add_model_parser,
)
from azathoth.cli.parsing.runs import (
    RUN_ACTION_ATTRIBUTE,
    RUN_COMMAND,
    RUN_FEEDBACK_ACTION,
    RUN_FEEDBACK_CORRECTED_OUTPUT_ATTRIBUTE,
    RUN_FEEDBACK_DISPOSITION_ATTRIBUTE,
    RUN_FEEDBACK_REASON_ATTRIBUTE,
    RUN_ID_ATTRIBUTE,
    RUN_SHOW_ACTION,
    add_run_parser,
)
from azathoth.cli.parsing.tools import (
    TOOL_ACTION_ATTRIBUTE,
    TOOL_COMMAND,
    TOOL_DOCUMENT_ATTRIBUTE,
    TOOL_ID_ATTRIBUTE,
    TOOL_IMPLEMENTATION_ID_ATTRIBUTE,
    TOOL_IMPLEMENTATION_SHOW_ACTION,
    TOOL_IMPLEMENTATIONS_ACTION,
    TOOL_IMPORT_ACTION,
    TOOL_LIST_ACTION,
    TOOL_SHOW_ACTION,
    TOOL_TEST_CASE_ID_ATTRIBUTE,
    TOOL_TEST_CASE_SHOW_ACTION,
    TOOL_TEST_CASES_ACTION,
    TOOL_USAGE_ACTION,
    TOOL_VERIFY_ACTION,
    TOOL_VERSION_ATTRIBUTE,
    TOOL_VERSIONS_ACTION,
    add_tool_parser,
)
from azathoth.cli.parsing.workflows import (
    EXPECTED_VALUE_ATTRIBUTE,
    GENERATIONS_ATTRIBUTE,
    TARGET_COST_ATTRIBUTE,
    TARGET_LATENCY_ATTRIBUTE,
    WORKFLOW_ACTION_ATTRIBUTE,
    WORKFLOW_COMMAND,
    WORKFLOW_DOCUMENT_ATTRIBUTE,
    WORKFLOW_EXPERIMENT_LIMIT_ATTRIBUTE,
    WORKFLOW_EXPERIMENTS_ACTION,
    WORKFLOW_ID_ATTRIBUTE,
    WORKFLOW_IMPORT_ACTION,
    WORKFLOW_INPUT_ATTRIBUTE,
    WORKFLOW_INVOKE_ACTION,
    WORKFLOW_LIST_ACTION,
    WORKFLOW_OPTIMIZE_ACTION,
    WORKFLOW_PROMOTE_ACTION,
    WORKFLOW_RUN_ACTION,
    WORKFLOW_RUN_LIMIT_ATTRIBUTE,
    WORKFLOW_RUNS_ACTION,
    WORKFLOW_SHOW_ACTION,
    add_workflow_parser,
)


def build_parser() -> ArgumentParser:
    """Build the Azathoth command-line parser."""

    parser = ArgumentParser(
        prog="azathoth",
        description="Empirical optimization for context-aware AI workflows.",
    )

    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    commands = parser.add_subparsers(
        dest=COMMAND_ATTRIBUTE,
    )

    add_workflow_parser(commands)

    add_run_parser(commands)

    add_experiment_parser(commands)

    add_model_parser(commands)

    add_tool_parser(commands)

    add_benchmark_parser(commands)

    add_goal_parser(commands)

    return parser


__all__ = [
    "BENCHMARK_ACTION_ATTRIBUTE",
    "BENCHMARK_CASES_ACTION",
    "BENCHMARK_CASE_ID_ATTRIBUTE",
    "BENCHMARK_CASE_SHOW_ACTION",
    "BENCHMARK_COMMAND",
    "BENCHMARK_COMPARE_ACTION",
    "BENCHMARK_DOCUMENT_ATTRIBUTE",
    "BENCHMARK_ID_ATTRIBUTE",
    "BENCHMARK_IMPORT_ACTION",
    "BENCHMARK_LIST_ACTION",
    "BENCHMARK_OUTPUT_ATTRIBUTE",
    "BENCHMARK_RUN_ACTION",
    "BENCHMARK_SHOW_ACTION",
    "BENCHMARK_WORKFLOW_IDS_ATTRIBUTE",
    "COMMAND_ATTRIBUTE",
    "EXPECTED_VALUE_ATTRIBUTE",
    "EXPERIMENT_ACTION_ATTRIBUTE",
    "EXPERIMENT_COMMAND",
    "EXPERIMENT_ID_ATTRIBUTE",
    "EXPERIMENT_SHOW_ACTION",
    "GENERATIONS_ATTRIBUTE",
    "GOAL_ACTION_ATTRIBUTE",
    "GOAL_COMMAND",
    "GOAL_DOCUMENT_ATTRIBUTE",
    "GOAL_ID_ATTRIBUTE",
    "GOAL_IMPORT_ACTION",
    "GOAL_LIST_ACTION",
    "GOAL_SHOW_ACTION",
    "MODEL_ACTION_ATTRIBUTE",
    "MODEL_AUTHORIZE_ACTION",
    "MODEL_COMMAND",
    "MODEL_DEAUTHORIZE_ACTION",
    "MODEL_FORCE_ATTRIBUTE",
    "MODEL_IDENTIFIER_ATTRIBUTE",
    "MODEL_LIST_ACTION",
    "MODEL_PORTFOLIO_ACTION",
    "MODEL_SHOW_ACTION",
    "MODEL_USAGE_ACTION",
    "RUN_ACTION_ATTRIBUTE",
    "RUN_COMMAND",
    "RUN_FEEDBACK_ACTION",
    "RUN_FEEDBACK_CORRECTED_OUTPUT_ATTRIBUTE",
    "RUN_FEEDBACK_DISPOSITION_ATTRIBUTE",
    "RUN_FEEDBACK_REASON_ATTRIBUTE",
    "RUN_ID_ATTRIBUTE",
    "RUN_SHOW_ACTION",
    "TARGET_COST_ATTRIBUTE",
    "TARGET_LATENCY_ATTRIBUTE",
    "TOOL_ACTION_ATTRIBUTE",
    "TOOL_COMMAND",
    "TOOL_DOCUMENT_ATTRIBUTE",
    "TOOL_ID_ATTRIBUTE",
    "TOOL_IMPLEMENTATION_ID_ATTRIBUTE",
    "TOOL_IMPLEMENTATIONS_ACTION",
    "TOOL_IMPLEMENTATION_SHOW_ACTION",
    "TOOL_IMPORT_ACTION",
    "TOOL_LIST_ACTION",
    "TOOL_SHOW_ACTION",
    "TOOL_TEST_CASES_ACTION",
    "TOOL_TEST_CASE_ID_ATTRIBUTE",
    "TOOL_TEST_CASE_SHOW_ACTION",
    "TOOL_USAGE_ACTION",
    "TOOL_VERIFY_ACTION",
    "TOOL_VERSION_ATTRIBUTE",
    "TOOL_VERSIONS_ACTION",
    "WORKFLOW_ACTION_ATTRIBUTE",
    "WORKFLOW_COMMAND",
    "WORKFLOW_DOCUMENT_ATTRIBUTE",
    "WORKFLOW_EXPERIMENT_LIMIT_ATTRIBUTE",
    "WORKFLOW_EXPERIMENTS_ACTION",
    "WORKFLOW_ID_ATTRIBUTE",
    "WORKFLOW_IMPORT_ACTION",
    "WORKFLOW_INPUT_ATTRIBUTE",
    "WORKFLOW_INVOKE_ACTION",
    "WORKFLOW_LIST_ACTION",
    "WORKFLOW_OPTIMIZE_ACTION",
    "WORKFLOW_PROMOTE_ACTION",
    "WORKFLOW_RUN_ACTION",
    "WORKFLOW_RUN_LIMIT_ATTRIBUTE",
    "WORKFLOW_RUNS_ACTION",
    "WORKFLOW_SHOW_ACTION",
    "add_benchmark_parser",
    "build_parser",
]
